<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Obscura.Application\Obscura.Application.csproj" />
    <ProjectReference Include="..\Obscura.Contracts\Obscura.Contracts.csproj" />
    <ProjectReference Include="..\Obscura.Domain\Obscura.Domain.csproj" />
    <ProjectReference Include="..\Obscura.Infrastructure\Obscura.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
