using Obscura.Application.System;

namespace Obscura.Application.Migrations;

/// <summary>
/// Application use-case service for v2 migration gates, fresh-start preparation, and legacy preview imports.
/// </summary>
public sealed class SystemMigrationService
{
    private readonly IV2UpgradeGate _gate;
    private readonly IV2FreshStartService _freshStart;
    private readonly ILegacyVideoImportService _legacyVideoImport;
    private readonly ILegacyMediaImportService _legacyMediaImport;
    private readonly ILegacyAssetNormalizationService _assetNormalization;

    /// <summary>
    /// Creates a system migration service over the migration ports implemented by infrastructure.
    /// </summary>
    /// <param name="gate">Upgrade consent gate.</param>
    /// <param name="freshStart">Fresh-start preparation port.</param>
    /// <param name="legacyVideoImport">Legacy video import port.</param>
    /// <param name="legacyMediaImport">Legacy non-video media import port.</param>
    /// <param name="assetNormalization">Post-import asset path normalization port.</param>
    public SystemMigrationService(
        IV2UpgradeGate gate,
        IV2FreshStartService freshStart,
        ILegacyVideoImportService legacyVideoImport,
        ILegacyMediaImportService legacyMediaImport,
        ILegacyAssetNormalizationService assetNormalization)
    {
        _gate = gate;
        _freshStart = freshStart;
        _legacyVideoImport = legacyVideoImport;
        _legacyMediaImport = legacyMediaImport;
        _assetNormalization = assetNormalization;
    }

    /// <summary>
    /// Gets the current v2 upgrade gate status in API contract form.
    /// </summary>
    /// <returns>Upgrade gate status response.</returns>
    public V2UpgradeGateStatusResult GetUpgradeGateStatus() => ToResult(_gate.Check());

    /// <summary>
    /// Accepts the v2 upgrade gate and returns the updated API contract.
    /// </summary>
    /// <returns>Accepted upgrade gate status response.</returns>
    public V2UpgradeGateStatusResult AcceptUpgradeGate() => ToResult(_gate.Accept());

    /// <summary>
    /// Re-arms the v2 upgrade gate for local migration testing. Truncates all v2 data
    /// and purges cache directories so the next migration run starts from a completely
    /// clean slate — no stale entities, files, or generated assets.
    /// </summary>
    /// <param name="cancellationToken">Token used to cancel the operation.</param>
    /// <returns>Prompted upgrade gate status response.</returns>
    public async Task<V2UpgradeGateStatusResult> PromptUpgradeGateAsync(CancellationToken cancellationToken)
    {
        await _freshStart.ClearPreparedAsync(cancellationToken);
        return ToResult(_gate.Prompt());
    }

    /// <summary>
    /// Prepares the v2 fresh-start reset when the upgrade gate has been accepted.
    /// Resets v2 media tables, purges the stale cache, preserves settings and
    /// library roots, then imports all legacy v1 data so that technical metadata,
    /// fingerprints, playback history, and relationships are retained. Thumbnails,
    /// previews, and trickplay sprites are regenerated by the first library rescan.
    /// </summary>
    /// <param name="cancellationToken">Token used to cancel the operation.</param>
    /// <returns>A successful response or a consent-required problem.</returns>
    public async Task<PrepareFreshStartResult> PrepareFreshStartAsync(CancellationToken cancellationToken)
    {
        var status = _gate.Check();
        if (!status.Accepted)
        {
            return PrepareFreshStartResult.Conflict(new ApplicationProblem(
                "v2_upgrade_consent_required",
                "Accept the v2 global entity upgrade gate before preparing the fresh-start migration."));
        }

        var result = await _freshStart.PrepareAsync(cancellationToken);

        LegacyVideoImportResult? videoImport = null;
        LegacyMediaImportResult? mediaImport = null;

        if (!result.AlreadyPrepared)
        {
            videoImport = await _legacyVideoImport.ImportAsync(cancellationToken);
            mediaImport = await _legacyMediaImport.ImportAsync(cancellationToken);
            await _assetNormalization.NormalizeAsync(cancellationToken);

            // Safety net: delete cache-generated entity_files that may have been
            // created by stale import SQL. Source files and custom legacy artwork
            // should survive migration; generated thumbnails, previews, sprites,
            // and trickplay frames are regenerated by the first library rescan.
            await _freshStart.PurgeNonSourceEntityFilesAsync(cancellationToken);
            await _freshStart.MarkPreparedAsync(cancellationToken);
        }

        return PrepareFreshStartResult.Prepared(new V2FreshStartPrepareResult(
            result.BackupPath,
            result.PreservedLibraryRoots,
            result.PreservedSettings,
            result.MediaReset,
            videoImport is null
                ? null
                : new LegacyVideoImportResultDto(
                    videoImport.SeriesImported,
                    videoImport.VideosImported,
                    videoImport.PeopleImported,
                    videoImport.TagsImported,
                    videoImport.StudiosImported,
                    videoImport.LinksImported),
            mediaImport is null
                ? null
                : new LegacyMediaImportResultDto(
                    mediaImport.ImagesImported,
                    mediaImport.GalleriesImported,
                    mediaImport.BooksImported,
                    mediaImport.AudioLibrariesImported,
                    mediaImport.AudioTracksImported,
                    mediaImport.CollectionsImported,
                    mediaImport.LinksImported)));
    }

    /// <summary>
    /// Imports legacy video data and returns API-ready import counts.
    /// </summary>
    /// <param name="cancellationToken">Token used to cancel the import.</param>
    /// <returns>Legacy video import counts.</returns>
    public async Task<LegacyVideoImportResultDto> ImportLegacyVideosAsync(CancellationToken cancellationToken)
    {
        var result = await _legacyVideoImport.ImportAsync(cancellationToken);
        return new LegacyVideoImportResultDto(
            result.SeriesImported,
            result.VideosImported,
            result.PeopleImported,
            result.TagsImported,
            result.StudiosImported,
            result.LinksImported);
    }

    /// <summary>
    /// Imports legacy media data and returns API-ready import counts.
    /// </summary>
    /// <param name="cancellationToken">Token used to cancel the import.</param>
    /// <returns>Legacy media import counts.</returns>
    public async Task<LegacyMediaImportResultDto> ImportLegacyMediaAsync(CancellationToken cancellationToken)
    {
        var result = await _legacyMediaImport.ImportAsync(cancellationToken);
        return new LegacyMediaImportResultDto(
            result.ImagesImported,
            result.GalleriesImported,
            result.BooksImported,
            result.AudioLibrariesImported,
            result.AudioTracksImported,
            result.CollectionsImported,
            result.LinksImported);
    }

    private static V2UpgradeGateStatusResult ToResult(V2UpgradeGateStatus status)
    {
        return new V2UpgradeGateStatusResult(status.GateId, status.Accepted);
    }
}

/// <summary>
/// Application result for preparing a v2 fresh-start reset.
/// </summary>
/// <param name="Response">Fresh-start response when preparation succeeds.</param>
/// <param name="Problem">Problem contract when preparation is blocked.</param>
public sealed record PrepareFreshStartResult(
    V2FreshStartPrepareResult? Response,
    ApplicationProblem? Problem)
{
    /// <summary>
    /// Creates a successful fresh-start preparation result.
    /// </summary>
    /// <param name="response">Application fresh-start response.</param>
    /// <returns>Successful preparation result.</returns>
    public static PrepareFreshStartResult Prepared(V2FreshStartPrepareResult response) => new(response, null);

    /// <summary>
    /// Creates a blocked fresh-start preparation result.
    /// </summary>
    /// <param name="problem">Problem explaining why preparation cannot continue.</param>
    /// <returns>Blocked preparation result.</returns>
    public static PrepareFreshStartResult Conflict(ApplicationProblem problem) => new(null, problem);
}
