namespace Obscura.Domain.Entities;

/// <summary>
/// Closed set of subtitle discovery or generation sources.
/// </summary>
public enum EntitySubtitleSource
{
    /// <summary>User supplied subtitle file.</summary>
    Manual,

    /// <summary>Subtitle stream extracted from source media.</summary>
    Embedded,

    /// <summary>Subtitle generated by a local service.</summary>
    Generated,

    /// <summary>Subtitle imported from a metadata or subtitle provider.</summary>
    Provider
}

/// <summary>
/// Codec for entity subtitle source codes.
/// </summary>
public sealed class EntitySubtitleSourceCodec : EnumCodec<EntitySubtitleSource>
{
    public EntitySubtitleSourceCodec()
        : base(new Dictionary<EntitySubtitleSource, string>
        {
            [EntitySubtitleSource.Manual] = "manual",
            [EntitySubtitleSource.Embedded] = "embedded",
            [EntitySubtitleSource.Generated] = "generated",
            [EntitySubtitleSource.Provider] = "provider"
        })
    {
    }
}
