// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obscura.Infrastructure.Persistence;

#nullable disable

namespace Obscura.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ObscuraDbContext))]
    [Migration("20260512144802_AddExpandedV2DataModel")]
    partial class AddExpandedV2DataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("v2")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.AudioLibraryDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("FolderPath")
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<Guid?>("ParentLibraryEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_library_entity_id");

                    b.Property<int>("TrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("track_count");

                    b.HasKey("EntityId");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("audio_library_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.AudioTrackDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int?>("BitRate")
                        .HasColumnType("integer")
                        .HasColumnName("bit_rate");

                    b.Property<int?>("Channels")
                        .HasColumnType("integer")
                        .HasColumnName("channels");

                    b.Property<string>("Codec")
                        .HasColumnType("text")
                        .HasColumnName("codec");

                    b.Property<string>("Container")
                        .HasColumnType("text")
                        .HasColumnName("container");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EmbeddedAlbum")
                        .HasColumnType("text")
                        .HasColumnName("embedded_album");

                    b.Property<string>("EmbeddedArtist")
                        .HasColumnType("text")
                        .HasColumnName("embedded_artist");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("integer")
                        .HasColumnName("sample_rate");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("track_number");

                    b.Property<string>("WaveformPath")
                        .HasColumnType("text")
                        .HasColumnName("waveform_path");

                    b.HasKey("EntityId");

                    b.ToTable("audio_track_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookChapterDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("ArchivePath")
                        .HasColumnType("text")
                        .HasColumnName("archive_path");

                    b.Property<Guid>("BookEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_entity_id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<Guid?>("CoverPageEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_page_entity_id");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<Guid?>("VolumeEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("volume_entity_id");

                    b.HasKey("EntityId");

                    b.HasIndex("ArchivePath")
                        .IsUnique();

                    b.HasIndex("BookEntityId", "ChapterNumber");

                    b.ToTable("book_chapter_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("BookType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("book_type");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_count");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_path");

                    b.Property<Guid?>("CoverPageEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_page_entity_id");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("FolderPath")
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<Guid?>("LibraryRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_root_id");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<string>("SortTitle")
                        .HasColumnType("text")
                        .HasColumnName("sort_title");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("EntityId");

                    b.HasIndex("LibraryRootId", "RelativePath")
                        .IsUnique();

                    b.ToTable("book_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookPageDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("BookEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_entity_id");

                    b.Property<Guid>("ChapterEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_entity_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("EntityId");

                    b.HasIndex("BookEntityId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("ChapterEntityId", "SortOrder");

                    b.ToTable("book_page_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookReadProgressRow", b =>
                {
                    b.Property<Guid>("BookEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_entity_id");

                    b.Property<Guid?>("ChapterEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_entity_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<int>("PageIndex")
                        .HasColumnType("integer")
                        .HasColumnName("page_index");

                    b.Property<string>("ReaderMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reader_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BookEntityId");

                    b.ToTable("book_read_progress", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookVolumeDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("BookEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_entity_id");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_path");

                    b.Property<string>("FolderPath")
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("volume_number");

                    b.HasKey("EntityId");

                    b.HasIndex("BookEntityId", "VolumeNumber")
                        .IsUnique();

                    b.ToTable("book_volume_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.CollectionDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_path");

                    b.Property<Guid?>("CoverItemEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_item_entity_id");

                    b.Property<string>("CoverMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cover_mode");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mode");

                    b.Property<string>("RuleTreeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_tree_json");

                    b.Property<bool>("SlideshowAutoAdvance")
                        .HasColumnType("boolean")
                        .HasColumnName("slideshow_auto_advance");

                    b.Property<int>("SlideshowDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("slideshow_duration_seconds");

                    b.HasKey("EntityId");

                    b.ToTable("collection_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.CollectionItemDetailRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("CollectionEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_entity_id");

                    b.Property<Guid>("ItemEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_entity_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ItemEntityId");

                    b.HasIndex("CollectionEntityId", "ItemEntityId")
                        .IsUnique();

                    b.ToTable("collection_item_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.DatabaseBackupRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_path");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("database_backups", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityAliasRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AliasType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("alias_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Value")
                        .IsUnique();

                    b.ToTable("entity_aliases", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityCreditLinkRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("PersonEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_entity_id");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Character")
                        .HasColumnType("text")
                        .HasColumnName("character");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("EntityId", "PersonEntityId", "Role");

                    b.HasIndex("PersonEntityId");

                    b.HasIndex("EntityId", "SortOrder");

                    b.ToTable("entity_credit_links", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityExternalIdRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("EntityId", "Provider")
                        .IsUnique();

                    b.ToTable("entity_external_ids", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFileFingerprintRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_file_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntityFileId");

                    b.HasIndex("EntityId", "Algorithm")
                        .IsUnique();

                    b.ToTable("entity_file_fingerprints", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Role")
                        .IsUnique();

                    b.ToTable("entity_files", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<bool>("IsOrganized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_organized");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityId");

                    b.ToTable("entity_flags", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityHierarchyLinkRow", b =>
                {
                    b.Property<Guid>("ParentEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_entity_id");

                    b.Property<Guid>("ChildEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_entity_id");

                    b.Property<string>("Relationship")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relationship");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("ParentEntityId", "ChildEntityId", "Relationship");

                    b.HasIndex("ChildEntityId");

                    b.HasIndex("ParentEntityId", "SortOrder");

                    b.ToTable("entity_hierarchy_links", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityKindRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.HasKey("Code");

                    b.ToTable("entity_kinds", "v2");

                    b.HasData(
                        new
                        {
                            Code = "video",
                            Category = "Media",
                            DisplayName = "Video"
                        },
                        new
                        {
                            Code = "video-series",
                            Category = "Media",
                            DisplayName = "Video Series"
                        },
                        new
                        {
                            Code = "image",
                            Category = "Media",
                            DisplayName = "Image"
                        },
                        new
                        {
                            Code = "gallery",
                            Category = "Media",
                            DisplayName = "Gallery"
                        },
                        new
                        {
                            Code = "book",
                            Category = "Media",
                            DisplayName = "Book"
                        },
                        new
                        {
                            Code = "audio",
                            Category = "Media",
                            DisplayName = "Audio"
                        },
                        new
                        {
                            Code = "audio-library",
                            Category = "Media",
                            DisplayName = "Audio Library"
                        },
                        new
                        {
                            Code = "audio-track",
                            Category = "Media",
                            DisplayName = "Audio Track"
                        },
                        new
                        {
                            Code = "person",
                            Category = "Taxonomy",
                            DisplayName = "Person"
                        },
                        new
                        {
                            Code = "studio",
                            Category = "Taxonomy",
                            DisplayName = "Studio"
                        },
                        new
                        {
                            Code = "tag",
                            Category = "Taxonomy",
                            DisplayName = "Tag"
                        },
                        new
                        {
                            Code = "collection",
                            Category = "Collection",
                            DisplayName = "Collection"
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityMarkerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("EndSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("end_seconds");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<double>("Seconds")
                        .HasColumnType("double precision")
                        .HasColumnName("seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Seconds");

                    b.ToTable("entity_markers", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityPlaybackRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<double>("PlayDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("play_duration_seconds");

                    b.Property<double>("ResumeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("resume_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityId");

                    b.ToTable("entity_playback", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("EntityId");

                    b.ToTable("entity_ratings", "v2", t =>
                        {
                            t.HasCheckConstraint("ck_entity_ratings_value", "value >= 0 AND value <= 5");
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("KindCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KindCode", "Title");

                    b.ToTable("entities", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityStudioLinkRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.HasKey("EntityId");

                    b.HasIndex("StudioId");

                    b.ToTable("entity_studio_links", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntitySubtitleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_format");

                    b.Property<string>("SourcePath")
                        .HasColumnType("text")
                        .HasColumnName("source_path");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Language", "Source")
                        .IsUnique();

                    b.ToTable("entity_subtitles", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityTagLinkRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EntityId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("entity_tag_links", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityUrlRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "SortOrder");

                    b.HasIndex("EntityId", "Url")
                        .IsUnique();

                    b.ToTable("entity_urls", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.FingerprintSubmissionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<Guid?>("ProviderConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_config_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId");

                    b.HasIndex("EntityId", "Algorithm", "Hash")
                        .IsUnique();

                    b.ToTable("fingerprint_submissions", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.GalleryDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("CoverImageEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_image_entity_id");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("FolderPath")
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<string>("GalleryType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gallery_type");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer")
                        .HasColumnName("image_count");

                    b.Property<string>("Photographer")
                        .HasColumnType("text")
                        .HasColumnName("photographer");

                    b.Property<string>("ZipFilePath")
                        .HasColumnType("text")
                        .HasColumnName("zip_file_path");

                    b.HasKey("EntityId");

                    b.HasIndex("FolderPath");

                    b.HasIndex("ZipFilePath");

                    b.ToTable("gallery_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.IdentifyResultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("MatchType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_type");

                    b.Property<string>("ProposedResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("proposed_result_json");

                    b.Property<Guid?>("ProviderConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_config_id");

                    b.Property<string>("RawResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId");

                    b.HasIndex("EntityId", "Status");

                    b.ToTable("identify_results", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.ImageDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("EntityId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("image_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.JobRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAt", "Priority");

                    b.ToTable("job_runs", "v2", t =>
                        {
                            t.HasCheckConstraint("ck_job_runs_attempts", "attempts >= 0 AND max_attempts > 0");

                            t.HasCheckConstraint("ck_job_runs_progress", "progress >= 0 AND progress <= 100");
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.LibraryRootRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool>("Recursive")
                        .HasColumnType("boolean")
                        .HasColumnName("recursive");

                    b.Property<bool>("ScanAudio")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_audio");

                    b.Property<bool>("ScanBooks")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_books");

                    b.Property<bool>("ScanImages")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_images");

                    b.Property<bool>("ScanVideos")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_videos");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("library_roots", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.LibrarySettingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoGenerateFingerprints")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_fingerprints");

                    b.Property<bool>("AutoGenerateMetadata")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_metadata");

                    b.Property<bool>("AutoGeneratePreview")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_preview");

                    b.Property<bool>("AutoScanEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_scan_enabled");

                    b.Property<int>("BackgroundWorkerConcurrency")
                        .HasColumnType("integer")
                        .HasColumnName("background_worker_concurrency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultPlaybackMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_playback_mode");

                    b.Property<bool>("GeneratePhash")
                        .HasColumnType("boolean")
                        .HasColumnName("generate_phash");

                    b.Property<bool>("GenerateTrickplay")
                        .HasColumnType("boolean")
                        .HasColumnName("generate_trickplay");

                    b.Property<bool>("HideNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_nsfw");

                    b.Property<bool>("MetadataStorageDedicated")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_storage_dedicated");

                    b.Property<bool>("NsfwLanAutoEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("nsfw_lan_auto_enable");

                    b.Property<int>("PreviewClipDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("preview_clip_duration_seconds");

                    b.Property<int>("ScanIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("scan_interval_minutes");

                    b.Property<bool>("ShowCastControls")
                        .HasColumnType("boolean")
                        .HasColumnName("show_cast_controls");

                    b.Property<float>("SubtitleFontScale")
                        .HasColumnType("real")
                        .HasColumnName("subtitle_font_scale");

                    b.Property<float>("SubtitleOpacity")
                        .HasColumnType("real")
                        .HasColumnName("subtitle_opacity");

                    b.Property<float>("SubtitlePositionPercent")
                        .HasColumnType("real")
                        .HasColumnName("subtitle_position_percent");

                    b.Property<string>("SubtitleStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle_style");

                    b.Property<bool>("SubtitlesAutoEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("subtitles_auto_enable");

                    b.Property<string>("SubtitlesPreferredLanguages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitles_preferred_languages");

                    b.Property<int>("ThumbnailQuality")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_quality");

                    b.Property<int>("TrickplayIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("trickplay_interval_seconds");

                    b.Property<int>("TrickplayQuality")
                        .HasColumnType("integer")
                        .HasColumnName("trickplay_quality");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("library_settings", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.MediaFileIgnoreRow", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityKindCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_kind_code");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason");

                    b.HasKey("Path");

                    b.HasIndex("EntityKindCode");

                    b.ToTable("media_file_ignores", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.PersonDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Birthdate")
                        .HasColumnType("text")
                        .HasColumnName("birthdate");

                    b.Property<int?>("CareerEnd")
                        .HasColumnType("integer")
                        .HasColumnName("career_end");

                    b.Property<int?>("CareerStart")
                        .HasColumnType("integer")
                        .HasColumnName("career_start");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Disambiguation")
                        .HasColumnType("text")
                        .HasColumnName("disambiguation");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("text")
                        .HasColumnName("ethnicity");

                    b.Property<string>("EyeColor")
                        .HasColumnType("text")
                        .HasColumnName("eye_color");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("HairColor")
                        .HasColumnType("text")
                        .HasColumnName("hair_color");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Measurements")
                        .HasColumnType("text")
                        .HasColumnName("measurements");

                    b.Property<string>("Piercings")
                        .HasColumnType("text")
                        .HasColumnName("piercings");

                    b.Property<string>("Tattoos")
                        .HasColumnType("text")
                        .HasColumnName("tattoos");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("EntityId");

                    b.ToTable("person_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.ProviderConfigRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_code");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCode")
                        .IsUnique();

                    b.ToTable("provider_configs", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.ProviderCredentialRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("credential_key");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_value");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_config_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId", "CredentialKey")
                        .IsUnique();

                    b.ToTable("provider_credentials", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.StudioDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ParentStudioEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_studio_entity_id");

                    b.HasKey("EntityId");

                    b.ToTable("studio_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.TagDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IgnoreAutoTag")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_auto_tag");

                    b.Property<Guid?>("ParentTagEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_tag_entity_id");

                    b.HasKey("EntityId");

                    b.ToTable("tag_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.UiPreferenceRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Key");

                    b.ToTable("ui_prefs", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int?>("BitRate")
                        .HasColumnType("integer")
                        .HasColumnName("bit_rate");

                    b.Property<string>("Codec")
                        .HasColumnType("text")
                        .HasColumnName("codec");

                    b.Property<string>("Container")
                        .HasColumnType("text")
                        .HasColumnName("container");

                    b.Property<string>("ContentRating")
                        .HasColumnType("text")
                        .HasColumnName("content_rating");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("double precision")
                        .HasColumnName("frame_rate");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid?>("LibraryRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_root_id");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("text")
                        .HasColumnName("release_date");

                    b.Property<string>("SortTitle")
                        .HasColumnType("text")
                        .HasColumnName("sort_title");

                    b.Property<DateTimeOffset?>("SubtitlesExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subtitles_extracted_at");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("EntityId");

                    b.HasIndex("LibraryRootId");

                    b.ToTable("video_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoSeasonDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("AirDate")
                        .HasColumnType("text")
                        .HasColumnName("air_date");

                    b.Property<string>("FolderPath")
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<Guid>("SeriesEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_entity_id");

                    b.HasKey("EntityId");

                    b.HasIndex("SeriesEntityId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("video_season_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoSeriesDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("ContentRating")
                        .HasColumnType("text")
                        .HasColumnName("content_rating");

                    b.Property<string>("EndAirDate")
                        .HasColumnType("text")
                        .HasColumnName("end_air_date");

                    b.Property<string>("FirstAirDate")
                        .HasColumnType("text")
                        .HasColumnName("first_air_date");

                    b.Property<string>("FolderPath")
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<Guid?>("LibraryRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_root_id");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<string>("RenderingMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rendering_mode");

                    b.Property<string>("SortTitle")
                        .HasColumnType("text")
                        .HasColumnName("sort_title");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.HasKey("EntityId");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.HasIndex("LibraryRootId");

                    b.ToTable("video_series_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.AudioLibraryDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.AudioLibraryDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.AudioTrackDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.AudioTrackDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookChapterDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("BookEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.BookChapterDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.BookDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.LibraryRootRow", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookPageDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("BookEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("ChapterEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.BookPageDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookReadProgressRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.BookReadProgressRow", "BookEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.BookVolumeDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("BookEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.BookVolumeDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.CollectionDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.CollectionDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.CollectionItemDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("CollectionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("ItemEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityAliasRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityCreditLinkRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("PersonEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityExternalIdRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFileFingerprintRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityFileRow", null)
                        .WithMany()
                        .HasForeignKey("EntityFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFileRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityHierarchyLinkRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("ChildEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("ParentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityMarkerRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityPlaybackRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityPlaybackRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityKindRow", null)
                        .WithMany()
                        .HasForeignKey("KindCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityStudioLinkRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityStudioLinkRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntitySubtitleRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityTagLinkRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityUrlRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.FingerprintSubmissionRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.ProviderConfigRow", null)
                        .WithMany()
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.GalleryDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.GalleryDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.IdentifyResultRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.ProviderConfigRow", null)
                        .WithMany()
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.ImageDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.ImageDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.PersonDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.PersonDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.ProviderCredentialRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.ProviderConfigRow", null)
                        .WithMany()
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.StudioDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.StudioDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.TagDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.TagDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.LibraryRootRow", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoSeasonDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.VideoSeasonDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoSeriesDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.VideoSeriesDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.LibraryRootRow", null)
                        .WithMany()
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
