// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Obscura.Infrastructure.Persistence;

#nullable disable

namespace Obscura.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ObscuraDbContext))]
[Migration("20260513001500_AddCapabilityFirstTables")]
partial class AddCapabilityFirstTables
{
}
