// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obscura.Infrastructure.Persistence;

#nullable disable

namespace Obscura.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ObscuraDbContext))]
    [Migration("20260512030313_AddV2EntityFiles")]
    partial class AddV2EntityFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("v2")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.DatabaseBackupRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_path");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("database_backups", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Role")
                        .IsUnique();

                    b.ToTable("entity_files", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<bool>("IsOrganized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_organized");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityId");

                    b.ToTable("entity_flags", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityKindRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.HasKey("Code");

                    b.ToTable("entity_kinds", "v2");

                    b.HasData(
                        new
                        {
                            Code = "video",
                            Category = "Media",
                            DisplayName = "Video"
                        },
                        new
                        {
                            Code = "image",
                            Category = "Media",
                            DisplayName = "Image"
                        },
                        new
                        {
                            Code = "gallery",
                            Category = "Media",
                            DisplayName = "Gallery"
                        },
                        new
                        {
                            Code = "book",
                            Category = "Media",
                            DisplayName = "Book"
                        },
                        new
                        {
                            Code = "audio",
                            Category = "Media",
                            DisplayName = "Audio"
                        },
                        new
                        {
                            Code = "performer",
                            Category = "Taxonomy",
                            DisplayName = "Performer"
                        },
                        new
                        {
                            Code = "studio",
                            Category = "Taxonomy",
                            DisplayName = "Studio"
                        },
                        new
                        {
                            Code = "tag",
                            Category = "Taxonomy",
                            DisplayName = "Tag"
                        },
                        new
                        {
                            Code = "collection",
                            Category = "Collection",
                            DisplayName = "Collection"
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("EntityId");

                    b.ToTable("entity_ratings", "v2", t =>
                        {
                            t.HasCheckConstraint("ck_entity_ratings_value", "value >= 0 AND value <= 5");
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("KindCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KindCode", "Title");

                    b.ToTable("entities", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityTagLinkRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EntityId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("entity_tag_links", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.JobRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAt", "Priority");

                    b.ToTable("job_runs", "v2", t =>
                        {
                            t.HasCheckConstraint("ck_job_runs_attempts", "attempts >= 0 AND max_attempts > 0");

                            t.HasCheckConstraint("ck_job_runs_progress", "progress >= 0 AND progress <= 100");
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.LibraryRootRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool>("Recursive")
                        .HasColumnType("boolean")
                        .HasColumnName("recursive");

                    b.Property<bool>("ScanAudio")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_audio");

                    b.Property<bool>("ScanBooks")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_books");

                    b.Property<bool>("ScanImages")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_images");

                    b.Property<bool>("ScanVideos")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_videos");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("library_roots", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.LibrarySettingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoGenerateFingerprints")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_fingerprints");

                    b.Property<bool>("AutoGenerateMetadata")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_metadata");

                    b.Property<bool>("AutoGeneratePreview")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_preview");

                    b.Property<bool>("AutoScanEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_scan_enabled");

                    b.Property<int>("BackgroundWorkerConcurrency")
                        .HasColumnType("integer")
                        .HasColumnName("background_worker_concurrency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultPlaybackMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_playback_mode");

                    b.Property<bool>("GeneratePhash")
                        .HasColumnType("boolean")
                        .HasColumnName("generate_phash");

                    b.Property<bool>("GenerateTrickplay")
                        .HasColumnType("boolean")
                        .HasColumnName("generate_trickplay");

                    b.Property<bool>("HideNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_nsfw");

                    b.Property<bool>("MetadataStorageDedicated")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_storage_dedicated");

                    b.Property<bool>("NsfwLanAutoEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("nsfw_lan_auto_enable");

                    b.Property<int>("PreviewClipDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("preview_clip_duration_seconds");

                    b.Property<int>("ScanIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("scan_interval_minutes");

                    b.Property<bool>("ShowCastControls")
                        .HasColumnType("boolean")
                        .HasColumnName("show_cast_controls");

                    b.Property<float>("SubtitleFontScale")
                        .HasColumnType("real")
                        .HasColumnName("subtitle_font_scale");

                    b.Property<float>("SubtitleOpacity")
                        .HasColumnType("real")
                        .HasColumnName("subtitle_opacity");

                    b.Property<float>("SubtitlePositionPercent")
                        .HasColumnType("real")
                        .HasColumnName("subtitle_position_percent");

                    b.Property<string>("SubtitleStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle_style");

                    b.Property<bool>("SubtitlesAutoEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("subtitles_auto_enable");

                    b.Property<string>("SubtitlesPreferredLanguages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitles_preferred_languages");

                    b.Property<int>("ThumbnailQuality")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_quality");

                    b.Property<int>("TrickplayIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("trickplay_interval_seconds");

                    b.Property<int>("TrickplayQuality")
                        .HasColumnType("integer")
                        .HasColumnName("trickplay_quality");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("library_settings", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("EntityId");

                    b.ToTable("video_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFileRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityKindRow", null)
                        .WithMany()
                        .HasForeignKey("KindCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityTagLinkRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
