// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obscura.Infrastructure.Persistence;

#nullable disable

namespace Obscura.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ObscuraDbContext))]
    partial class ObscuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("v2")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<bool>("IsOrganized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_organized");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityId");

                    b.ToTable("entity_flags", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityKindRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.HasKey("Code");

                    b.ToTable("entity_kinds", "v2");

                    b.HasData(
                        new
                        {
                            Code = "video",
                            Category = "Media",
                            DisplayName = "Video"
                        },
                        new
                        {
                            Code = "image",
                            Category = "Media",
                            DisplayName = "Image"
                        },
                        new
                        {
                            Code = "gallery",
                            Category = "Media",
                            DisplayName = "Gallery"
                        },
                        new
                        {
                            Code = "book",
                            Category = "Media",
                            DisplayName = "Book"
                        },
                        new
                        {
                            Code = "audio",
                            Category = "Media",
                            DisplayName = "Audio"
                        },
                        new
                        {
                            Code = "performer",
                            Category = "Taxonomy",
                            DisplayName = "Performer"
                        },
                        new
                        {
                            Code = "studio",
                            Category = "Taxonomy",
                            DisplayName = "Studio"
                        },
                        new
                        {
                            Code = "tag",
                            Category = "Taxonomy",
                            DisplayName = "Tag"
                        },
                        new
                        {
                            Code = "collection",
                            Category = "Collection",
                            DisplayName = "Collection"
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("EntityId");

                    b.ToTable("entity_ratings", "v2", t =>
                        {
                            t.HasCheckConstraint("ck_entity_ratings_value", "value >= 0 AND value <= 5");
                        });
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("KindCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KindCode", "Title");

                    b.ToTable("entities", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityTagLinkRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EntityId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("entity_tag_links", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("EntityId");

                    b.ToTable("video_details", "v2");
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityFlagRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.EntityRatingRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityKindRow", null)
                        .WithMany()
                        .HasForeignKey("KindCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.EntityTagLinkRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", b =>
                {
                    b.HasOne("Obscura.Infrastructure.Persistence.Entities.EntityRow", null)
                        .WithOne()
                        .HasForeignKey("Obscura.Infrastructure.Persistence.Entities.VideoDetailRow", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
